[package]
name = "hello-from-generated-code-4"
version = "0.1.0"
authors = ["聂小涛 <niexiaotao@bytedance.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libloading = "0.5.2"