[package]
name = "hello-from-generated-code-3"
version = "0.1.0"
authors = ["聂小涛 <niexiaotao@bytedance.com>"]
edition = "2018"
links = "z"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
